import axios from "axios";

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiJjYi5zYy51NGNzZTIzNjE4QGNiLnN0dWRlbnRzLmFtcml0YS5lZHUiLCJleHAiOjE3NzgwNjY1NzMsImlhdCI6MTc3ODA2NTY3MywiaXNzIjoiQWZmb3JkIE1lZGljYWwgVGVjaG5vbG9naWVzIFByaXZhdGUgTGltaXRlZCIsImp0aSI6ImUwZTQ0ZGEwLTAwYWEtNGNjYi1iZjJiLTk2NDBmNjVmNjE1NCIsImxvY2FsZSI6ImVuLUlOIiwibmFtZSI6InJhbmdhIGFydW4ga3VtYXIiLCJzdWIiOiJmNTU0NDdiOS03YzE5LTQ3MjktODE3Yy1jMzkwMDRhMjc2MWMifSwiZW1haWwiOiJjYi5zYy51NGNzZTIzNjE4QGNiLnN0dWRlbnRzLmFtcml0YS5lZHUiLCJuYW1lIjoicmFuZ2EgYXJ1biBrdW1hciIsInJvbGxObyI6ImNiLnNjLnU0Y3NlMjMxOCIsImFjY2Vzc0NvZGUiOiJQVEJNbVEiLCJjbGllbnRJRCI6ImY1NTQ0N2I5LTdjMTktNDcyOS04MTdjLWMzOTAwNGEyNzYxYyIsImNsaWVudFNlY3JldCI6IldkdEpldXJ1UkJFeG5kTWsifQ.IoDSsVYBhs9HB4BHeFA4ZZkvQ6QDY7dhp7wJYXgmODc";

const api = axios.create({
  baseURL:
    "http://20.207.122.201/evaluation-service",
  headers: {
    Authorization: `Bearer ${token}`,
  },
});

export default api;